services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s
      ports:
        - 8212:8212/udp
        - 27016:27016/udp
        - 8212:8212/tcp  # REST API port
      env_file:
        - .env
      environment:
         PUID: 1000
         PGID: 1000
         PORT: 8212
         PLAYERS: 16
         SERVER_PASSWORD: 'salehB0ss'
         MULTITHREADING: "true"
         RCON_ENABLED: "false"
         REST_API_ENABLED: "true"
         REST_API_PORT: 8212
         TZ: "UTC"
         ADMIN_PASSWORD: 'salehB0ss'
         COMMUNITY: "true"
         SERVER_NAME: "Bandar Enstek by Loki"
         SERVER_DESCRIPTION: "palworld running on a docker by SalehLoke"
         ALLOW_CONNECT_PLATFORM: "Steam"
      volumes:
         - ./palworld:/palworld/
         - ./save:/home/steam/Pal/Saved/SaveGames/
         - ./config:/palworld/Pal/Saved/Config/LinuxServer/
